// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDMiRTo3YTRGxmaT3oyAkDz_JiEWKWBXSk",
    authDomain: "goldenheart-3372b.firebaseapp.com",
    projectId: "goldenheart-3372b",
    storageBucket: "goldenheart-3372b.firebasestorage.app",
    messagingSenderId: "28271795580",
    appId: "1:28271795580:android:f10d2e251adf332cb418f9",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAc3N7tXegS9tXOzHIm_rl5IlJzOS9GdxY",
    authDomain: "goldenheart-3372b.firebaseapp.com",
    projectId: "goldenheart-3372b",
    storageBucket: "goldenheart-3372b.firebasestorage.app",
    messagingSenderId: "28271795580",
    appId: "1:28271795580:ios:360bc9ebc13c7537b418f9",
  );
}
